export const QUESTION_LIST_REQUEST = 'QUESTION_LIST_REQUEST'
export const QUESTION_LIST_RESPONSE = 'QUESTION_LIST_RESPONSE'

export const ADD_QUESTION_REQUEST = 'ADD_QUESTION_REQUEST'
export const ADD_QUESTION_RESPONSE = 'ADD_QUESTION_RESPONSE'
export const ADD_QUIZ_REQUEST = 'ADD_QUIZ_REQUEST'
export const ADD_QUIZ_RESPONSE = 'ADD_QUIZ_RESPONSE'
export const QUIZ_LIST_REQUEST = 'QUIZ_LIST_REQUEST'
export const QUIZ_LIST_RESPONSE = 'QUIZ_LIST_RESPONSE'